#!/bin/bash

 docker run --name firewall-updater -d \
  -v /mnt/secrets/gcp-service-account.json:/usr/src/app/google_service_account.json \
  -e GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/google_service_account.json \
  -e PROJECT_ID=personal-1101 \
  -e FIREWALL_RULE_NAME=allow-home-ip \
  -e NETWORK_NAME=default \
  -e CRON_EXPRESSION='* * * * *' \
  firewall-updater:latest
